python/django/django_intro/dojo_survey/app_one/urls.py
from django.urls import path
from . import views

app_name = 'survey'

urlpatterns = [
    path('', views.index, name='my_index'),
    path('result', views.result, name='my_result')
]

python/django/django_intro/dojo_survey/dojo_survey/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app_one.urls')),
    # path('admin/', admin.site.urls),
]

python/django/django_intro/dojo_survey/app_one/views.py
from django.shortcuts import render, redirect

# Create your views here.


def index(request):
    return render(request, "index.html")


def result(request):
    context = {
        "name": request.POST["name"],
        "location": request.POST["location"],
        "language": request.POST["language"],
        "comments": request.POST["comments"],
    }
    return render(request, "result.html", context)

python/django/django_intro/dojo_survey/app_one/templates/index.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>Dojo Survey</title>
</head>

<body>
    <div class="container">
        <h1>Dojo Survey</h1>
        <form action="{% url 'survey:my_result' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="name" class="form-label">Name:</label>
                <input type="text" class="form-control" name="name">
            </div>
            <div class="mb-3">
                <label for="location" class="form-label">Dojo Location:</label>
                <select class="form-select" aria-label="" name="location">
                    <option selected>-- Select A Location --</option>
                    <option value="Chicago">Chicago</option>
                    <option value="Seattke">Seattle</option>
                    <option value="Online">Online</option>
                    <option value="Burbank">Burbank</option>
                    <option value="Bellevue">Bellevue</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="language" class="form-label">Favorite Language:</label>
                <select class="form-select" aria-label="Favorite Language" name="language">
                    <option selected>-- Select A Language --</option>
                    <option value="HTML">HTML</option>
                    <option value="CSS">CSS</option>
                    <option value="JavaScript">JavaScript</option>
                    <option value="Python">Python</option>
                    <option value="C#">C#</option>
                    <option value="Other">Other</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="comments" class="form-label">Comments:</label>
                <textarea class="form-control" name="comments" style="height: 100px"></textarea>
            </div>
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>

</html>

python/django/django_intro/dojo_survey/app_one/templates/result.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-sc">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>Dojo Survey</title>
</head>

<body>
    <div class="container">
        <h1>Submitted Info</h1>
        <div class="card p-3 m-3 shadow">
            <p>Name: {{name}}</p>
            <p>Dojo Location: {{location}}</p>
            <p>Favorite Language: {{language}}</p>
            <p>Comments: {{comments}}</p>
        </div>
        <a href="{% url 'survey:my_index' %}" class="btn btn-primary" type="submit">Go Back</a>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>

</html>